import pandas as pd

df_product_detail = pd.read_excel("./商品收发明细表-20220707175818.xls")
# 过滤无用数据
# 聚合计算总的销量
# 计算总销售天数
# 计算平均销量
# 计算预计消耗天数


data = [{'thor_user_id': 'F7HLqJiSBfKR', 'name': '小量2', 'company': {'name': '珠海比量', 'id': 'blzh'},
         'tel': '13392966503',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'bl_test_2', 'name': '小量2', 'department': [10], 'position': '', 'mobile': '13392966503', 'gender': '1',
                              'email': '', 'avatar': 'http://wework.qpic.cn/bizmail/7KrgcloJZQvExoHtlp6EZJ3SI6Tl6wAltU1whV26icGr6BVzSsA4icsw/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '小量2', 'telephone': '', 'enable': 1,
                              'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 10,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcab15384ca6e94b8f', 'alias': '小量2', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/7KrgcloJZQvExoHtlp6EZJ3SI6Tl6wAltU1whV26icGr6BVzSsA4icsw/100', 'direct_leader': [],
                              'biz_mail': 'xiaoliang2@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_Nmrr9ePMFg'},
        {'thor_user_id': '4A4HHJy4PCqc', 'name': '郑敏怡', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '18813498771',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '95', 'name': '郑敏怡', 'department': [2], 'position': '行政助理', 'mobile': '18813498771', 'gender': '2',
                              'email': '1036498828@qq.com', 'avatar': 'http://wework.qpic.cn/bizmail/DhDlky5ELfbKgS6ccSvOyX0JAAibF55VYWdyxxHGRJUICIXHn2k5icOg/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 2,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc90dbeb9171598aca', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/DhDlky5ELfbKgS6ccSvOyX0JAAibF55VYWdyxxHGRJUICIXHn2k5icOg/100', 'direct_leader': [],
                              'biz_mail': 'zhengminyi@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_CqNbzShYUH'},
        {'thor_user_id': '6RJW6A4ehbHr', 'name': '刘林', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '17600760964',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '86', 'name': '刘林', 'department': [3], 'position': '产品经理', 'mobile': '17600760964', 'gender': '1',
                              'email': '812837570@qq.com', 'avatar': 'http://wework.qpic.cn/bizmail/Adkgw4hCiaSq8Qy1lf3ccibtpfZ93ZbXMZKJIbiaBJmxyhRdMbIGyagBQ/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc604d0f8248ee6595', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/Adkgw4hCiaSq8Qy1lf3ccibtpfZ93ZbXMZKJIbiaBJmxyhRdMbIGyagBQ/100', 'direct_leader': [],
                              'biz_mail': 'liulin@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_vcQA2Z9rkE'},
        {'thor_user_id': '4Yz8jTb26vYJ', 'name': '罗雨', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '17688199204',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '90', 'name': '罗雨', 'department': [3], 'position': '运维工程师', 'mobile': '17688199204', 'gender': '1',
                              'email': 'lrain9712@126.com', 'avatar': 'http://wework.qpic.cn/bizmail/RSsRXulwUXPh92EkkbJyqYn8qaqiahffj2aia2ZObTjeVAlK0H1zKjPw/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcaac16ffb5c5bc959', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/RSsRXulwUXPh92EkkbJyqYn8qaqiahffj2aia2ZObTjeVAlK0H1zKjPw/100', 'direct_leader': [],
                              'biz_mail': 'luoyu@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_M4ghZ9tt5c'},
        {'thor_user_id': 'dFtnZ2uPmVuH', 'name': '肖镇城', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13631262395',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '18', 'name': '肖镇城', 'department': [3], 'position': 'Python研发工程师', 'mobile': '13631262395', 'gender': '2',
                              'email': '441990625@qq.com', 'avatar': 'http://wework.qpic.cn/wwhead/duc2TvpEgST9hicuyypLEKMWbodsJyHM0vic0uu3ZSGb7YqkwelDpZDvOYUTKoEk1tMO3tHBn450U/0',
                              'status': 1, 'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '比量',
                              'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''},
                              'main_department': 3, 'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcef3bdfc10a6d56be', 'alias': '比量',
                              'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/wwhead/duc2TvpEgST9hicuyypLEKMWbodsJyHM0vic0uu3ZSGb7YqkwelDpZDvOYUTKoEk1tMO3tHBn450U/100', 'direct_leader': [],
                              'biz_mail': 'xiaozhencheng@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_ZBmTwkgfbE'},
        {'thor_user_id': '83vYT9mX2n2K', 'name': '龙武画', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13411570225',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '46', 'name': '龙武画', 'department': [3], 'position': 'UI交互设计师', 'mobile': '13411570225', 'gender': '1',
                              'email': '178091684@qq.com',
                              'avatar': 'https://wework.qpic.cn/wwhead/dx4Y70y9XcvSiazHvUicn0E2lAR1I1pnRLxsS5haXA7Uz6uNQFd2wic7FoQeEu6ZRJAWsSibTFlS4TY/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [2147383647],
                              'main_department': 3, 'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc5a952e9d949979f6', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwhead/dx4Y70y9XcvSiazHvUicn0E2lAR1I1pnRLxsS5haXA7Uz6uNQFd2wic7FoQeEu6ZRJAWsSibTFlS4TY/100',
                              'direct_leader': [], 'biz_mail': 'longwuhua@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_pENe9pWwQv'},
        {'thor_user_id': '7WhdNnC8kwZZ', 'name': '冯荣坤', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '18565234401',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '61', 'name': '冯荣坤', 'department': [3], 'position': 'Python研发工程师', 'mobile': '18565234401', 'gender': '2',
                              'email': 'frk2008@163.com', 'avatar': 'https://wework.qpic.cn/wwhead/duc2TvpEgST9hicuyypLEKN5F0z4QSlg2vg0xGRJCAKibOsGyGPyXuVxKExC9ymBwtPZZTeJFnhwU/0',
                              'status': 1, 'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '比量科技', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [2147383647],
                              'external_profile': {'external_attr': [{'type': 0, 'name': '昵称', 'text': {'value': '冯'}}]}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc492ea4b23a591cf2', 'alias': '比量科技', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwhead/duc2TvpEgST9hicuyypLEKN5F0z4QSlg2vg0xGRJCAKibOsGyGPyXuVxKExC9ymBwtPZZTeJFnhwU/100',
                              'direct_leader': [], 'biz_mail': 'fengrongkun@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_psFLu6S2EA'},
        {'thor_user_id': '57VdY4HPyL9v', 'name': '黄龙', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '15207561400',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '80', 'name': '黄龙', 'department': [3], 'position': 'Android开发工程师', 'mobile': '15207561400', 'gender': '1',
                              'email': '704480904@qq.com', 'avatar': 'http://wework.qpic.cn/bizmail/iaQiaqfag6SWjEv9RIBnh1I0T7gyzPck4OaibZm4Mibwgicb6bOSvkE8g0Q/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcaf913c9d134f22a3', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/iaQiaqfag6SWjEv9RIBnh1I0T7gyzPck4OaibZm4Mibwgicb6bOSvkE8g0Q/100', 'direct_leader': [],
                              'biz_mail': 'huanglong@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_RGaRxPMLwH'},
        {'thor_user_id': '4RGGH4UqFPpF', 'name': '王赢', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '15976931823',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '94', 'name': '王赢', 'department': [3], 'position': 'Python开发', 'mobile': '15976931823', 'gender': '1',
                              'email': 'wpp_work_mail@163.com', 'avatar': 'http://wework.qpic.cn/bizmail/B2jMr5qrViaZKJicHDicXlJl9alYNvBHt5lcmhvR7G0wXUiblQGVBjkV2Q/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc79fd1253e0665e82', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/B2jMr5qrViaZKJicHDicXlJl9alYNvBHt5lcmhvR7G0wXUiblQGVBjkV2Q/100', 'direct_leader': [],
                              'biz_mail': 'wangying@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_Wpt4PEeKqv'},
        {'thor_user_id': '7GabeahBoNxr', 'name': '韦玉宝', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '18778189892',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '98', 'name': '韦玉宝', 'department': [3], 'position': '前端开发工程师', 'mobile': '18778189892', 'gender': '1',
                              'email': '', 'avatar': 'http://wework.qpic.cn/bizmail/ib6Oatb7MbQia4opSD2lWNubNYQwjsDCnJVkfXX4LOH2ics5drMqDjCdw/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '', 'enable': 1,
                              'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc62c4e14c2732cf80', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/ib6Oatb7MbQia4opSD2lWNubNYQwjsDCnJVkfXX4LOH2ics5drMqDjCdw/100', 'direct_leader': [],
                              'biz_mail': 'weiyubao@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_PjTZyhGhAP'},
        {'thor_user_id': '65x8Yc4r4G68', 'name': '李沅锟', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '19120553416',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '97', 'name': '李沅锟', 'department': [3], 'position': 'Python开发', 'mobile': '19120553416', 'gender': '1',
                              'email': '', 'avatar': 'http://wework.qpic.cn/bizmail/bVumibzkWEhkN2rSYArtTad44SVTKxRia35jTYIGnfdtq37kqiaJwJmEA/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '', 'enable': 1,
                              'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcd884de469961d32a', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/bVumibzkWEhkN2rSYArtTad44SVTKxRia35jTYIGnfdtq37kqiaJwJmEA/100', 'direct_leader': [],
                              'biz_mail': 'liyuankun@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': ''},
        {'thor_user_id': 'kbkh76FtSN97', 'name': '唐延安', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '18875243292',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '99', 'name': '唐延安', 'department': [3], 'position': '前端开发工程师', 'mobile': '18875243292', 'gender': '1',
                              'email': '1413938599@qq.com', 'avatar': 'https://wework.qpic.cn/bizmail/dgBDz8BiaEp5BVatMdib5zDLjEYnciaAKYlxQFAyzXhiasBGyrXMfoQfpg/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc12557a7bcc82af99', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'https://wework.qpic.cn/bizmail/dgBDz8BiaEp5BVatMdib5zDLjEYnciaAKYlxQFAyzXhiasBGyrXMfoQfpg/100', 'direct_leader': [],
                              'biz_mail': 'tangyanan@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': ''},
        {'thor_user_id': '6DWtJhjAAzDa', 'name': '娜姐', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13925223421',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'S0001', 'name': '娜姐', 'department': [5], 'position': '', 'mobile': '13925223421', 'gender': '2', 'email': '',
                              'avatar': 'http://shp.qpic.cn/bizmp/2fgN9n827GmUf566wTPvvrulHurg7IgDKvcv2iagp8et1CNXRQsnfHw/', 'status': 1, 'isleader': 0, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 5,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc8e7e0cddfd0692c6', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'http://shp.qpic.cn/bizmp/2fgN9n827GmUf566wTPvvrulHurg7IgDKvcv2iagp8et1CNXRQsnfHw/100', 'direct_leader': [],
                              'biz_mail': 'najie@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_jtiu4w2NHo'},
        {'thor_user_id': '6bRh2SMuqPZX', 'name': '吴正伟', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13676067853',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'A00001', 'name': '吴正伟', 'department': [6], 'position': '分公司负责人', 'mobile': '13676067853', 'gender': '1',
                              'email': 'puzhizhuhai@outlook.com', 'avatar': 'http://shp.qpic.cn/bizmp/2fgN9n827GmiaicGCrMjByEhiaJ9ktKRqkpFdTOR47GFslUrgKd453gqQ/', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '吴正伟123', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 6,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcd49c189b96f69fb9', 'alias': '吴正伟123', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'http://shp.qpic.cn/bizmp/2fgN9n827GmiaicGCrMjByEhiaJ9ktKRqkpFdTOR47GFslUrgKd453gqQ/100', 'direct_leader': [],
                              'biz_mail': 'wuzhengwei@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_dSYRg9mMNz'},
        {'thor_user_id': '6oTaKHugaowE', 'name': '万老师', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13923365234',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'A00000', 'name': '万老师', 'department': [6], 'position': '分公司负责人', 'mobile': '13923365234', 'gender': '1',
                              'email': 'zhwanli@foxmail.com', 'avatar': 'http://wework.qpic.cn/bizmail/yhDibVXddO0eAibxC4qJkRvNOaEM7SmhoYrr0o9jC2dJgnReM2ldFWdQ/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 6,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcb630564b9843931a', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/yhDibVXddO0eAibxC4qJkRvNOaEM7SmhoYrr0o9jC2dJgnReM2ldFWdQ/100', 'direct_leader': [],
                              'biz_mail': 'wanlaoshi@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_ZPQNHxSHjD'},
        {'thor_user_id': '4zNJCiqv6zD9', 'name': '小量', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13392967793',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'XiaoLiang13392967793', 'name': '小量', 'department': [7], 'position': '', 'mobile': '13392967793',
                              'gender': '2', 'email': '', 'avatar': 'http://wework.qpic.cn/bizmail/BWquic1HVORCrsuPSuHm6Ys6V1ZQP0M1JSlBxvJ4bQIjExlA5kozvKQ/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '小量1', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0],
                              'external_profile': {'external_attr': [{'type': 0, 'name': '昵称', 'text': {'value': '小小量'}}], 'external_corp_name': ''}, 'main_department': 7,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc886e25f0a54363bd', 'alias': '小量1', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/BWquic1HVORCrsuPSuHm6Ys6V1ZQP0M1JSlBxvJ4bQIjExlA5kozvKQ/100', 'direct_leader': [],
                              'biz_mail': 'xiaoliang@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_gtcb7KjYSK'},
        {'thor_user_id': '5Rpg6yNpKa4b', 'name': '比量科技公用打印机', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'SenHuaQuan', 'name': '比量科技公用打印机', 'department': [1], 'position': '', 'mobile': '', 'gender': '1',
                              'email': '', 'avatar': 'https://wework.qpic.cn/wwpic/118765_Ou6vWMKvSEqKiph_1655170180/0', 'status': 1, 'isleader': 0, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 1,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc16764a4e525e2303', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwpic/118765_Ou6vWMKvSEqKiph_1655170180/0', 'direct_leader': [],
                              'biz_mail': 'senhuaquan@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': ''},
        {'thor_user_id': '7926pYV2QSfh', 'name': '张欣', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13612811975',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'zxin', 'name': '张欣', 'department': [5], 'position': '销售助理', 'mobile': '13612811975', 'gender': '1',
                              'email': '', 'avatar': 'https://wework.qpic.cn/bizmail/K3UXhkVTlKxUMv5ibbTsmicL4Ker7M8NMSNOZ52qrIOzQKSW19jv1b2w/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 5,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc68c42a66bab6976c', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/bizmail/K3UXhkVTlKxUMv5ibbTsmicL4Ker7M8NMSNOZ52qrIOzQKSW19jv1b2w/100', 'direct_leader': [],
                              'biz_mail': 'zxin@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_PiUGbHTsac'},
        {'thor_user_id': '8BfSjHZcwpyL', 'name': '杨超峰', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'YangChaoFeng', 'name': '杨超峰', 'department': [5], 'position': '销售助理', 'mobile': '', 'gender': '1',
                              'email': '', 'avatar': 'https://wework.qpic.cn/wwpic/844915_u4QwJd8TSsSBZn3_1652858357/0', 'status': 5, 'isleader': 0, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 5,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc01176c8579ce9f1f', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwpic/844915_u4QwJd8TSsSBZn3_1652858357/0', 'direct_leader': [],
                              'biz_mail': 'yangchaofeng@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': ''},
        {'thor_user_id': 'qDSHuKX7upyZ', 'name': '彭亮', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13751019930',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'MuMu', 'name': '彭亮', 'department': [5], 'position': '销售经理', 'mobile': '13751019930', 'gender': '1',
                              'email': '', 'avatar': 'https://wework.qpic.cn/wwpic/265319_CShHVEz0Sy6nRvx_1650506267/0', 'status': 1, 'isleader': 1, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 5,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc09774e4a67e51137', 'alias': '', 'is_leader_in_dept': [1],
                              'thumb_avatar': 'https://wework.qpic.cn/wwpic/265319_CShHVEz0Sy6nRvx_1650506267/0', 'direct_leader': [], 'biz_mail': 'mumu@blkj14.onexmail.com'},
         'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_rjX92zBjM2'},
        {'thor_user_id': '3SYmqKfq3wkD', 'name': '韦伟', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'YiFan', 'name': '韦伟', 'department': [5], 'position': '销售经理', 'mobile': '', 'gender': '1', 'email': '',
                              'avatar': 'https://wework.qpic.cn/bizmail/mtxlKWWTdrHLYNEENqqiabLicnbRtGwkjdsetPb8WgwRJ3CoeibibUqvhA/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 5,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc49b9faa7c3d346b2', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/bizmail/mtxlKWWTdrHLYNEENqqiabLicnbRtGwkjdsetPb8WgwRJ3CoeibibUqvhA/100', 'direct_leader': [],
                              'biz_mail': 'yifan@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': ''},
        {'thor_user_id': '6BQQx3VKL39R', 'name': '刘巍', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '18008484821',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'liu@', 'name': '刘巍', 'department': [3], 'position': '行政人事', 'mobile': '18008484821', 'gender': '2',
                              'email': '', 'avatar': 'http://wework.qpic.cn/bizmail/uhuwJ1b1FfXwPTqBOoibrbw0nvupD5qgYPUILHjbiaia1s749RPUef58g/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '', 'enable': 1,
                              'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcc1f0e291d7b46de4', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/uhuwJ1b1FfXwPTqBOoibrbw0nvupD5qgYPUILHjbiaia1s749RPUef58g/100', 'direct_leader': [],
                              'biz_mail': 'liu@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_fDssSkt3fv'},
        {'thor_user_id': 'cmiFXdADyaCp', 'name': '吴正伟', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13676067853',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'ZH00001', 'name': '吴正伟', 'department': [2], 'position': '', 'mobile': '13676067853', 'gender': '1',
                              'email': 'wuzhengwei@blkj14.onexmail.com', 'avatar': 'http://shp.qpic.cn/bizmp/LNc9ZGVTw75yXJCPNxxfDq4YxrjLIccDrC35P7VQkakc6qMaPwupmg/', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 2,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vceedb36a23d3a7bc2', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'http://shp.qpic.cn/bizmp/LNc9ZGVTw75yXJCPNxxfDq4YxrjLIccDrC35P7VQkakc6qMaPwupmg/100', 'direct_leader': [],
                              'biz_mail': 'wuzhengwei@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_dSYRg9mMNz'},
        {'thor_user_id': 'nFjUm6pzsp8c', 'name': '万里', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13923365234',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'ZH0001', 'name': '万里', 'department': [2], 'position': '珠海分公司负责人', 'mobile': '13923365234', 'gender': '1',
                              'email': 'wanli@blkj14.onexmail.com', 'avatar': 'http://wework.qpic.cn/bizmail/yhDibVXddO0eAibxC4qJkRvNOaEM7SmhoYrTrbcJbfL2pkjHTsOuicMtQ/0',
                              'status': 1, 'isleader': 1, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '',
                              'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 2,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcc3cbe4f1b271a2ae', 'alias': '', 'is_leader_in_dept': [1], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/yhDibVXddO0eAibxC4qJkRvNOaEM7SmhoYrTrbcJbfL2pkjHTsOuicMtQ/100', 'direct_leader': [],
                              'biz_mail': 'wanli@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_ZPQNHxSHjD'},
        {'thor_user_id': '4ufpFmGuVG4h', 'name': '董琴', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13600167208',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'dongqin', 'name': '董琴', 'department': [4], 'position': '会计', 'mobile': '13600167208', 'gender': '2',
                              'email': 'dongqin@blkj14.onexmail.com', 'avatar': 'http://wework.qpic.cn/bizmail/KRGkpYKc4JFAUkKF0okiaYump1h7z9BicX0uQaxJaPKmorT0uOiaqYgcA/',
                              'status': 1, 'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [2147383647],
                              'main_department': 4, 'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc215cdaf5ba8639ac', 'alias': '', 'is_leader_in_dept': [0],
                              'address': '', 'thumb_avatar': 'http://wework.qpic.cn/bizmail/KRGkpYKc4JFAUkKF0okiaYump1h7z9BicX0uQaxJaPKmorT0uOiaqYgcA/100', 'direct_leader': [],
                              'biz_mail': 'dongqin@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': ''},
        {'thor_user_id': '6F4j7Jai9gGM', 'name': '黄娜', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13925223421',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'A00000', 'name': '黄娜', 'department': [11], 'position': '总经理', 'mobile': '13925223421', 'gender': '2',
                              'email': 'huangna@blkj14.onexmail.com', 'avatar': 'http://shp.qpic.cn/bizmp/LNc9ZGVTw75yXJCPNxxfDq4YxrjLIccDlupykFMS5VBE3Ya3SM5MdA/', 'status': 1,
                              'isleader': 1, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [2147383647], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 11,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc613d8ff887081065', 'alias': '', 'is_leader_in_dept': [1], 'address': '',
                              'thumb_avatar': 'http://shp.qpic.cn/bizmp/LNc9ZGVTw75yXJCPNxxfDq4YxrjLIccDlupykFMS5VBE3Ya3SM5MdA/100', 'direct_leader': [],
                              'biz_mail': 'huangna@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_jtiu4w2NHo'},
        {'thor_user_id': '5qTnQCwnYb4u', 'name': '柯观培', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '15976530892',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'k_1', 'name': '柯观培', 'department': [12], 'position': '客服', 'mobile': '15976530892', 'gender': '1',
                              'email': '', 'avatar': 'https://wework.qpic.cn/wwpic/37465_fdOKqVNETRyoDag_1653069286/0', 'status': 1, 'isleader': 0, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 12,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc579b8d63a4d056cf', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwpic/37465_fdOKqVNETRyoDag_1653069286/0', 'direct_leader': [], 'biz_mail': 'k1@blkj14.onexmail.com'},
         'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_dkmkCRGtuP'},
        {'thor_user_id': 'VMjeSWHhgpwV', 'name': '刘峰', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '18310788339',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'greasi', 'name': '刘峰', 'department': [12], 'position': '客服', 'mobile': '18310788339', 'gender': '1',
                              'email': '', 'avatar': 'https://wework.qpic.cn/wwpic/156807_pXVmxqptSIiP9u9_1655114713/0', 'status': 1, 'isleader': 0, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 12,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcab8ac73c4845edc7', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwpic/156807_pXVmxqptSIiP9u9_1655114713/0', 'direct_leader': [], 'biz_mail': 'greasi@blkj14.onexmail.com'},
         'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': ''},
        {'thor_user_id': 'vrFR6TXZeBNv', 'name': '张慧玫', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '19530776191',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'k', 'name': '张慧玫', 'department': [12], 'position': '客服', 'mobile': '19530776191', 'gender': '2', 'email': '',
                              'avatar': 'https://wework.qpic.cn/wwpic/309155_CtknZ3B9TOiHKM4_1650249733/0', 'status': 1, 'isleader': 0, 'extattr': {'attrs': []},
                              'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 12,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vce9803ca29dfeebc0', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/wwpic/309155_CtknZ3B9TOiHKM4_1650249733/0', 'direct_leader': [], 'biz_mail': 'k@blkj14.onexmail.com'},
         'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': ''},
        {'thor_user_id': '3RneG5NZpPXV', 'name': '姚晓琪', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13798562762',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'aki.', 'name': '姚晓琪', 'department': [13], 'position': '文案策划', 'mobile': '13798562762', 'gender': '2',
                              'email': '', 'avatar': 'https://wework.qpic.cn/bizmail/37bXmt6wJ10zkXqibNrYQNm6dHK5KCyXyuNtIiaEcYOIsZa0YkaKOIVA/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 13,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc4f2adfcc241c0a07', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/bizmail/37bXmt6wJ10zkXqibNrYQNm6dHK5KCyXyuNtIiaEcYOIsZa0YkaKOIVA/100', 'direct_leader': [],
                              'biz_mail': 'aki@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_eaMLWiUp9n'},
        {'thor_user_id': '6ZZC5WCgk4YG', 'name': '胡清', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '13870414752',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'Nan', 'name': '胡清', 'department': [13], 'position': '文案策划', 'mobile': '13870414752', 'gender': '2',
                              'email': '', 'avatar': 'https://wework.qpic.cn/bizmail/gicNFXSMChPJoIoocehsZa8nIN70H8IRjSxzLVicKbz899DpZRRNrL4g/0', 'status': 1, 'isleader': 0,
                              'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 13,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcc0a028a999c44d86', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/bizmail/gicNFXSMChPJoIoocehsZa8nIN70H8IRjSxzLVicKbz899DpZRRNrL4g/100', 'direct_leader': [],
                              'biz_mail': 'nan@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_RoftBSP8pm'},
        {'thor_user_id': '7tEXPkP6D7G8', 'name': '李莲莲', 'company': {'name': '比量深圳', 'id': 'blsz'}, 'tel': '18325139641',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': 'HongDouShengNanGuo', 'name': '李莲莲', 'department': [13], 'position': '文案策划', 'mobile': '18325139641',
                              'gender': '2', 'email': '', 'avatar': 'https://wework.qpic.cn/bizmail/zBs9zHNrlWSIBoQ7IG9icMVOG6f3m1h1oZBok4xfQ1lZPWuuwKuIg4A/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': []}, 'english_name': '', 'telephone': '', 'enable': 1, 'hide_mobile': 0, 'order': [0], 'main_department': 13,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc78942c38fe2ff393', 'alias': '', 'is_leader_in_dept': [0],
                              'thumb_avatar': 'https://wework.qpic.cn/bizmail/zBs9zHNrlWSIBoQ7IG9icMVOG6f3m1h1oZBok4xfQ1lZPWuuwKuIg4A/100', 'direct_leader': [],
                              'biz_mail': 'hongdoushengnanguo1@blkj14.onexmail.com'}, 'corpid': 'wx345d6f1495d98490', 'disable': None, 'user_id': 'u_bK9MbNgER4'},
        {'thor_user_id': 'Xhv9NyGZGdqq', 'name': '周志敏', 'company': {'name': '比量珠海', 'id': 'blzh'}, 'tel': '13612213365',
         'wechat_user_info': {'errcode': 0, 'errmsg': 'ok', 'userid': '89', 'name': '周志敏', 'department': [3], 'position': '测试工程师', 'mobile': '13612213365', 'gender': '1',
                              'email': '1600137189@qq.com', 'avatar': 'http://wework.qpic.cn/bizmail/S13Tonhh7odqkNOAL3crpicx4yicJljs2TqVyicO9InCq15CG47bZSuhA/0', 'status': 1,
                              'isleader': 0, 'extattr': {'attrs': [{'name': '英文名', 'value': '', 'type': 0, 'text': {'value': ''}}]}, 'english_name': '', 'telephone': '',
                              'enable': 1, 'hide_mobile': 0, 'order': [0], 'external_profile': {'external_attr': [], 'external_corp_name': ''}, 'main_department': 3,
                              'qr_code': 'https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc3134f93ff3403be8', 'alias': '', 'is_leader_in_dept': [0], 'address': '',
                              'thumb_avatar': 'http://wework.qpic.cn/bizmail/S13Tonhh7odqkNOAL3crpicx4yicJljs2TqVyicO9InCq15CG47bZSuhA/100', 'direct_leader': [],
                              'biz_mail': 'zhouzhimin@zhbl2.wecom.work'}, 'corpid': 'wxd1a9235ca9807bd7', 'disable': None, 'user_id': 'u_RUTDnqXBEr'}]
user_list = []
for index, employee_info in enumerate(data):
    user_id = employee_info.get("user_id", "")
    if user_id:
        name = employee_info.get("name")
        user_id = employee_info.get("user_id")
        print(index, name,user_id)
        user_list.append(user_id)

print(len(user_list))
#
# for index, item in enumerate(data):
#     name = item.get("name")
#     print(index, name)
