# 2、将时间字符转为int型数据

new_data_list = [1, 2, 3, 4, 5, 8, 9]
# new_data_list = [arrow.get(x, 'YYYY-MM-DD').toordinal() for x in date_list]
sort_new_data_list = sorted(new_data_list, key=lambda x: int(x))
date_len = len(new_data_list)
sign_in_count = 0
for i in range(date_len):
    diff = sort_new_data_list[date_len - 1] - sort_new_data_list[i]
    value_range = len(sort_new_data_list[i:])
    if diff == value_range - 1:
        sign_in_count = value_range
        break

print(sign_in_count)

data = {'sendstatus': '1', 'payment_entry': [
    {'settleaccountid_name': '微信小商店', 'paid_amount': '1216', 'pay_comment': None, 'paytypeid_name': '微信支付', 'settleaccountid_id': '1403709214135695360',
     'id': '1545032604363786243', 'transnumber': None, 'amountfor': '1216', 'paytypeid_id': '3', 'seq': '1', 'settleaccountid_number': '1003'}],
        'creatorid_masterid': '0',
        'deliveryman_view': '', 'alldebt': '0',
        'currencyid_amtprecision': '2', 'subsist_info': '0', 'importflag': False,
        'currencyid_name': '人民币', 'basecurrency_exctype': '2',
        'inputcoefficient_option': 'obverse', 'totalinsamountfor': '1216', 'requiredinvoice': True,
        'customerid_rate': '0', 'cus_currency_name': '人民币', 'multiple_pay_info': None,
        'allocur_rule': '0', 'basecurrency_number': 'CNY', 'delivery_type_name': '物流发货',
        'basecurrency_enable': '1', 'basecurrency_convertmode': '1',
        'billtypeid_modeltype': 'BillFormModel', 'billsource': 'SCM', 'invoicecode': '',
        'outersrcinterid': '0', 'invoicestatus': '1', 'cus_currency_priceprecision': '2',
        'attachments': '0', 'modifierid_phone': '13392967793', 'delivery_type_id': '6',
        'bill_deal_amount': '1216', 'customerid_name': '朱念_omvAI5aCStkVbqRv9fKKXMn1Cd1g',
        'wf_previoushandler': '', 'dispatcher_country_masterid': '1000001', 'recevice_delivery': '',
        'dbcreatetime': '2022-11-02 17:43:59', 'payment_flag': True,
        'createtime': '2022-11-02 17:43:05', 'basecurrency_rate': '1', 'totalinsamount': '1216',
        'basecurrency_format': '', 'currencyid_format': '', 'sum_whole_amt_bef_dis': '0',
        'voucherid': '0', 'invoiceremark': None, 'modifierid_username': '',
        'basecurrency_sign': '', 'billtypeid_name': '销售出库单', 'customerid_bank': '',
        'customerid_bankaccount': '', 'totalinsfinalamountfor': '1216', 'cus_currency_rate': '1', 'customerid_remark': '', 'invoicedamount': '0', 'deduction_balance': '0',
        'wf_currentnode': '', 'modifierid_masterid': '0', 'attachments_url': [], 'cus_currency_amtprecision': '2', 'basecurrency_isshowsign': False, 'fee_entity': [],
        'alter_version': '000', 'cost_fee': '0', 'audittime': '2022-11-02', 'dbmodifytime': '2022-11-02 17:47:26', 'whole_discount_flag': True, 'currencyid_convertmode': '1',
        'curdebtbalance': '0', 'change_whole_dis_flag': '', 'modifytime': '2022-11-02 17:47:26', 'exchangerate': '1', 'returnstatus': 'A', 'customerid_enable': '1',
        'voucherno': '', 'wf_progress': None, 'vrp_delivery_time_view': '', 'deduction_entry': [],
        'delivery_billno_view': '[{"text":"SF6091802719541","url":"https://www.kuaidi100.com?nu=SF6091802719541"}]',
        'delivery_type_number': 'JHFS01', 'vehicle_view': '',
        'contact_address': '广东省深圳市福田区南园街道沙埔头西村36栋', 'creatorid_id': '10174784', 'customerid_taxpayerno': '', 'auditorid_username': '',
        'modifierid_number': 'qywx_woecicwaa6uysadjsgaw', 'cus_currency_convertmode': '1', 'totalsettleamountfor': '1216', 'driver_view': '', 'currencyid_sign': '',
        'basecurrency_amtprecision': '2', 'diffamountfor': '0', 'duedate': '2022-11-02', 'creatorid_username': '', 'express_entity': [
        {'express_company_commont': '', 'express_company_number': 'SF', 'delivery_billno': 'SF6091802719541', 'express_company_id': '1', 'id': '1545034243069970432',
         'express_company_name': '顺丰快递', 'delivery_time': '', 'express_remark': '', 'express_company_enable': '1', 'seq': '1'}], 'contact_country_name': '中国', 'printcount': 0,
        'contact_linkman': '朱念', 'express_remark_view': '', 'cus_currency_isshowsign': False, 'auditorid_phone': '18680321827', 'currencyid_exctype': '2', 'accountchecktime': '',
        'contact_country_masterid': '1000001', 'cost_fee_entity': {'feeRecords': []}, 'totalunsettleamount': '0', 'settlestatus': 'C', 'dispatcher_country_id': '1000001',
        'creatorid_name': '小量', 'cus_currency_number': 'CNY', 'id': '1545032604363787264', 'lastdebt': '0', 'cost_fee_for': '0', 'creatorid_phone': '13392967793', 'transtype': '2',
        'material_entity': [
            {'material_set_price': '0', 'baseunit_number': '支', 'taxamountfor': '0', 'srcentryid': '1545030645204387840', 'materialid_net_weight': '0', 'entryinvoicedamount': '0',
             'taxprice': '178', 'outersrcentryid': '0', 'proregno': '', 'stockid_isallowneg': False, 'stockid_remark': '', 'unittype': '0', 'stockid_isallowfreight': False,
             'linkfeefor': '0', 'auxpropname': None, 'aux_price': '0', 'material_remark_export': '', 'materialid_costprice': '0', 'cost_view': '0', 'ref_retail_price': '280',
             'material_set_name': None, 'batchno': '', 'totalnetweight': '0', 'materialid_isasstattr': True, 'auxpropid_seqno': '1', 'materialid_secinventoryqty': '0',
             'feefor': '0', 'auxcoefficient': '0', 'inv_baseqty': '0', 'entrystatus': 'Z', 'dividediffamount': '0', 'baseunit_precisionaccount': '2', 'actnontaxprice': '178',
             'sn': None, 'caculatecoefficient': '0', 'seq': '1', 'custom_entity_field__data': None, 'invoicedactnontaxamount': '0', 'baseqty': '4', 'package1': '', 'package0': '',
             'cess': '0', 'package3': '', 'stockid_number': 'SZCK0001', 'package2': '', 'materialid_gross_weight': '0', 'unit_precisionaccount': '2', 'validdate': '',
             'materialid_high': '0', 'is_free': False, 'disprice': '178', 'totalfeefor': '0', 'materialid_costmethod': '1', 'dividediffamountfor': '0', 'aux_taxprice': '0',
             'materialid_isbatch': False, 'materialid_maxpurchaseprice': '0', 'auxpropid_name': '净含量', 'unsettleamountfor': '0', 'sn_list': '', 'srcbilltypeid_name': '销售订单',
             'totalfee': '0', 'auxpropid_id': '1528323421727933440', 'materialid_istaxfree': False, 'barcode': '', 'materialid_length': '0', 'returndeffloatqty': '0',
             'allamountfor': '712', 'proplace': '', 'materialid_ischangeduedatetype': '', 'volume': '0', 'baseunit_name': '支', 'cursettleamountfor': '712', 'expectprofit': '0',
             'qty': '4.0000000000', 'coefficient': '1', 'materialid_helpcode': '', 'deffloatqty': '0', 'totalvolume': '0', 'auxpropid_skuid': '1528323421006512128',
             'entrusttaxamountfor': '0', 'srcinterid': '1545030643862210560', 'cursettleamount': '712', 'materialid_retailprice': '0', 'materialid_leadtime': '0',
             'srcbilltypeid_modeltype': 'BillFormModel', 'package_view': '4支', 'unit_precision': '0', 'predisamount': '712', 'balanceamount': '0', 'order_qty': '0',
             'auxpropid_url': '', 'allamount': '712', 'commonunitcost_view': '0', 'materialid_ismulti_unit': False, 'materialid_volume': '0', 'baseunit_conversiontype': '1',
             'comment': None, 'material_band_export': '', 'instantqty': '433', 'is_promote_free': '', 'stockid_name': '深圳仓库', 'discount': '10', 'snlistid': '0', 'price': '178',
             'materialid_refistrationnumber': '', 'id': '1545032604363786240', 'stockid_mobile': '', 'srcorderid': 'sxo_20221102161317631600', 'returnbaseqty': '0',
             'materialid_iskfperiod': False, 'materialid_ispurchase': True, 'materialid_wide': '0', 'order_baseqty': '4', 'baseunit_id': '3', 'stockid_phone': '',
             'invoicedtaxamount': '0', 'auxid1_number': 'FZSX00547', 'mullabel': [], 'taxamount': '0', 'inputcoefficient': '0', 'materialid_barcode': '', 'baseunit_precision': '0',
             'materialid_prolicense': '', 'materialid_issale': True, 'returnqty': '0', 'materialid_maxinventoryqty': '0', 'custbillno': '', 'srcseq': '1', 'stockid_address': '',
             'src_billdate': '', 'src_bill_dis_rate': '0', 'invoiceddisamount': '0', 'materialid_duedatetype': '1', 'stockid_id': '1389149618935194624', 'disamount': '0',
             'materialid_tradeprice': '0', 'auxqty': '0', 'unit_id': '3', 'kfperiod': '0', 'materialid_bindsupplier': '', 'actnontaxamount': '712', 'entryinvoicestatus': '1',
             'materialid_name': '脉迪欣酵母重组胶原蛋白敷料贴', 'balanceamountfor': '0', 'regain_price': True, 'promote_ids': '', 'acttaxprice': '178', 'auxunittype': '0',
             'picture': 'https://allmark.oss-cn-shenzhen.aliyuncs.com/scarlet/limit/shopxo/2022-10-09/shopxo_xlkk_1665298180_98664?upload_id=upload_7NLisq5ns9tx',
             'materialid_entrust': False, 'invoicedbilldistribution': '0', 'entrustamountfor': '0', 'cusmaterial_model_export': '', 'returnbillno': '', 'settleamountfor': '712',
             'kftype': '', 'entryinvoicedqty': '0', 'auxpropid_concattypeid': '1528323412517241856', 'fee': '0', 'materialid_number': 'P_MDX_221009_01', 'materialid_model': '',
             'set_entry_qty': '0', 'net_weight': '0', 'entrusttaxamount': '0', 'unit_number': '支', 'serialqty': '0', 'materialid_kfperiodtype': '', 'gross_weight': '0',
             'unit_conversiontype': '1', 'auxprop_sku_export': '', 'package': '[["支",4.0,"3",1,0]]', 'inv_qty': '433', 'auxpropid_enable': '1', 'materialid_stockup_day': '3',
                 'auxpropid_number': 'K_MDX_221009_01', 'entrysettlestatus': 'C', 'set_entry_id': '0', 'srcbillno': 'sxo_20221102161317631600', 'unit_name': '支', 'entrustamount': '0',
             'material_model_export': '', 'srcbillno_hyperlink': ' ', 'promote_names': '', 'billdisdistribution': '0', 'settleamount': '712', 'auxid1_id': '1528323412517241856',
             'materialid_kfperiod': '0', 'linkfee': '0', 'materialid_purchaseprice': '0', 'unitcost': '0', 'materialid_taxrate': '0', 'disrate': '0',
             'auxpropid_materialid': '1528323421098786816', 'srcbilltypeid_id': 'sal_bill_order', 'srcbilltypeid_number': 'sal_bill_order', 'base_taxprice': '178',
             'eoutersrcinterid': '0', 'base_price': '178', 'prolicense': '', 'material_set_code': '', 'auxid1_name': '5P/盒', 'materialid_checktype': '1',
             'material_category_export': '', 'distaxamount': '0', 'amount': '712', 'cost': '0', 'totalgrossweight': '0', 'unitcost_view': '0', 'stockid_enable': '1', 'kfdate': '',
             'billdisbeforeamount': '712', 'materialid_isserial': False, 'unsettleamount': '0', 'materialid_minsalesprice': '0', 'materialid_producingpace': '',
             'materialid_mininventoryqty': '5', 'conversionrate': '', 'materialid_remark': '', 'materialid_id': '1528323421098786816'},
            {'material_set_price': '0', 'baseunit_number': '支', 'taxamountfor': '0', 'srcentryid': '1545030645204387841', 'materialid_net_weight': '0', 'entryinvoicedamount': '0',
             'taxprice': '168', 'outersrcentryid': '0', 'proregno': '', 'stockid_isallowneg': False, 'stockid_remark': '', 'unittype': '0', 'stockid_isallowfreight': False,
             'linkfeefor': '0', 'auxpropname': None, 'aux_price': '0', 'material_remark_export': '', 'materialid_costprice': '0', 'cost_view': '0', 'ref_retail_price': '168',
             'material_set_name': None, 'batchno': '', 'totalnetweight': '0', 'materialid_isasstattr': True, 'auxpropid_seqno': '1', 'materialid_secinventoryqty': '0',
             'feefor': '0', 'auxcoefficient': '0', 'inv_baseqty': '0', 'entrystatus': 'Z', 'dividediffamount': '0', 'baseunit_precisionaccount': '2', 'actnontaxprice': '168',
             'sn': None, 'caculatecoefficient': '0', 'seq': '2', 'custom_entity_field__data': None, 'invoicedactnontaxamount': '0', 'baseqty': '3', 'package1': '', 'package0': '',
             'cess': '0', 'package3': '', 'stockid_number': 'SZCK0001', 'package2': '', 'materialid_gross_weight': '0', 'unit_precisionaccount': '2', 'validdate': '',
             'materialid_high': '0', 'is_free': False, 'disprice': '168', 'totalfeefor': '0', 'materialid_costmethod': '1', 'dividediffamountfor': '0', 'aux_taxprice': '0',
             'materialid_isbatch': False, 'materialid_maxpurchaseprice': '0', 'auxpropid_name': '润泽补水面膜5片', 'unsettleamountfor': '0', 'sn_list': '', 'srcbilltypeid_name': '销售订单',
             'totalfee': '0', 'auxpropid_id': '1399311013483927552', 'materialid_istaxfree': False, 'barcode': '', 'materialid_length': '0', 'returndeffloatqty': '0',
             'allamountfor': '504', 'proplace': '', 'materialid_ischangeduedatetype': '1', 'volume': '0', 'baseunit_name': '支', 'cursettleamountfor': '504', 'expectprofit': '0',
             'qty': '3.0000000000', 'coefficient': '1', 'materialid_helpcode': '', 'deffloatqty': '0', 'totalvolume': '0', 'auxpropid_skuid': '1389953607494821888',
             'entrusttaxamountfor': '0', 'srcinterid': '1545030643862210560', 'cursettleamount': '504', 'materialid_retailprice': '168', 'materialid_leadtime': '0',
             'srcbilltypeid_modeltype': 'BillFormModel', 'package_view': '3支', 'unit_precision': '0', 'predisamount': '504', 'balanceamount': '0', 'order_qty': '0',
             'auxpropid_url': '', 'allamount': '504', 'commonunitcost_view': '0', 'materialid_ismulti_unit': False, 'materialid_volume': '0', 'baseunit_conversiontype': '1',
             'comment': None, 'material_band_export': '', 'instantqty': '190', 'is_promote_free': '', 'stockid_name': '深圳仓库', 'discount': '10', 'snlistid': '0', 'price': '168',
             'materialid_refistrationnumber': '', 'id': '1545032604363786241', 'stockid_mobile': '', 'srcorderid': 'sxo_20221102161317631600', 'returnbaseqty': '0',
             'materialid_iskfperiod': False, 'materialid_ispurchase': True, 'materialid_wide': '0', 'order_baseqty': '3', 'baseunit_id': '3', 'stockid_phone': '',
             'invoicedtaxamount': '0', 'auxid1_number': 'FZSX00098', 'mullabel': [], 'taxamount': '0', 'inputcoefficient': '0', 'materialid_barcode': '', 'baseunit_precision': '0',
             'materialid_prolicense': '', 'materialid_issale': True, 'returnqty': '0', 'materialid_maxinventoryqty': '0', 'custbillno': '', 'srcseq': '2', 'stockid_address': '',
             'src_billdate': '', 'src_bill_dis_rate': '0', 'invoiceddisamount': '0', 'materialid_duedatetype': '1', 'stockid_id': '1389149618935194624', 'disamount': '0',
             'materialid_tradeprice': '0', 'auxqty': '0', 'unit_id': '3', 'kfperiod': '0', 'materialid_bindsupplier': '', 'actnontaxamount': '504', 'entryinvoicestatus': '1',
             'materialid_name': '森花泉古方草本护肤系列 天门冬面膜45分钟直达真皮银耳深度补水', 'balanceamountfor': '0', 'regain_price': True, 'promote_ids': '', 'acttaxprice': '168', 'auxunittype': '0',
             'picture': 'https://mmecimage.cn/p/wxe6b89bd3689d4f57/HO9ulGV7f-lonvtgtolpTgEVvFN3rsVE1HuX-fPyrhM', 'materialid_entrust': False, 'invoicedbilldistribution': '0',
             'entrustamountfor': '0', 'cusmaterial_model_export': '', 'returnbillno': '', 'settleamountfor': '504', 'kftype': '', 'entryinvoicedqty': '0',
             'auxpropid_concattypeid': '1389953590776324096', 'fee': '0', 'materialid_number': 'P_SHQ_220406_69', 'materialid_model': '', 'set_entry_qty': '0', 'net_weight': '0',
             'entrusttaxamount': '0', 'unit_number': '支', 'serialqty': '0', 'materialid_kfperiodtype': '', 'gross_weight': '0', 'unit_conversiontype': '1',
             'auxprop_sku_export': '', 'package': '[["支",3.0,"3",1,0]]', 'inv_qty': '190', 'auxpropid_enable': '1', 'materialid_stockup_day': '3',
             'auxpropid_number': 'K_SHQ_MM_5P_0328', 'entrysettlestatus': 'C', 'set_entry_id': '0', 'srcbillno': 'sxo_20221102161317631600', 'unit_name': '支', 'entrustamount': '0',
             'material_model_export': '', 'srcbillno_hyperlink': ' ', 'promote_names': '', 'billdisdistribution': '0', 'settleamount': '504', 'auxid1_id': '1389953590776324096',
             'materialid_kfperiod': '0', 'linkfee': '0', 'materialid_purchaseprice': '0', 'unitcost': '0', 'materialid_taxrate': '0', 'disrate': '0',
             'auxpropid_materialid': '1399311012678622208', 'srcbilltypeid_id': 'sal_bill_order', 'srcbilltypeid_number': 'sal_bill_order', 'base_taxprice': '168',
             'eoutersrcinterid': '0', 'base_price': '168', 'prolicense': '', 'material_set_code': '', 'auxid1_name': '润泽补水面膜5片', 'materialid_checktype': '1',
             'material_category_export': '', 'distaxamount': '0', 'amount': '504', 'cost': '0', 'totalgrossweight': '0', 'unitcost_view': '0', 'stockid_enable': '1', 'kfdate': '',
             'billdisbeforeamount': '504', 'materialid_isserial': False, 'unsettleamount': '0', 'materialid_minsalesprice': '0', 'materialid_producingpace': '',
             'materialid_mininventoryqty': '0', 'conversionrate': '', 'materialid_remark': '', 'materialid_id': '1399311012678622208'},
            {'material_set_price': '0', 'baseunit_number': '支', 'taxamountfor': '0', 'srcentryid': '1545030645204387842', 'materialid_net_weight': '0', 'entryinvoicedamount': '0',
             'taxprice': '0', 'outersrcentryid': '0', 'proregno': '', 'stockid_isallowneg': False, 'stockid_remark': '', 'unittype': '0', 'stockid_isallowfreight': False,
             'linkfeefor': '0', 'auxpropname': None, 'aux_price': '0', 'material_remark_export': '', 'materialid_costprice': '0', 'cost_view': '0', 'ref_retail_price': '168',
             'material_set_name': None, 'batchno': '', 'totalnetweight': '0', 'materialid_isasstattr': True, 'auxpropid_seqno': '1', 'materialid_secinventoryqty': '0',
             'feefor': '0', 'auxcoefficient': '0', 'inv_baseqty': '0', 'entrystatus': 'Z', 'dividediffamount': '0', 'baseunit_precisionaccount': '2', 'actnontaxprice': '0',
             'sn': None, 'caculatecoefficient': '0', 'seq': '3', 'custom_entity_field__data': None, 'invoicedactnontaxamount': '0', 'baseqty': '1', 'package1': '', 'package0': '',
             'cess': '0', 'package3': '', 'stockid_number': 'SZCK0001', 'package2': '', 'materialid_gross_weight': '0', 'unit_precisionaccount': '2', 'validdate': '',
             'materialid_high': '0', 'is_free': False, 'disprice': '0', 'totalfeefor': '0', 'materialid_costmethod': '1', 'dividediffamountfor': '0', 'aux_taxprice': '0',
             'materialid_isbatch': False, 'materialid_maxpurchaseprice': '0', 'auxpropid_name': '润泽补水面膜5片', 'unsettleamountfor': '0', 'sn_list': '', 'srcbilltypeid_name': '销售订单',
             'totalfee': '0', 'auxpropid_id': '1399311013483927552', 'materialid_istaxfree': False, 'barcode': '', 'materialid_length': '0', 'returndeffloatqty': '0',
             'allamountfor': '0', 'proplace': '', 'materialid_ischangeduedatetype': '1', 'volume': '0', 'baseunit_name': '支', 'cursettleamountfor': '0', 'expectprofit': '0',
             'qty': '1.0000000000', 'coefficient': '1', 'materialid_helpcode': '', 'deffloatqty': '0', 'totalvolume': '0', 'auxpropid_skuid': '1389953607494821888',
             'entrusttaxamountfor': '0', 'srcinterid': '1545030643862210560', 'cursettleamount': '0', 'materialid_retailprice': '168', 'materialid_leadtime': '0',
             'srcbilltypeid_modeltype': 'BillFormModel', 'package_view': '1支', 'unit_precision': '0', 'predisamount': '0', 'balanceamount': '0', 'order_qty': '0',
             'auxpropid_url': '', 'allamount': '0', 'commonunitcost_view': '0', 'materialid_ismulti_unit': False, 'materialid_volume': '0', 'baseunit_conversiontype': '1',
             'comment': None, 'material_band_export': '', 'instantqty': '190', 'is_promote_free': '', 'stockid_name': '深圳仓库', 'discount': '10', 'snlistid': '0', 'price': '0',
             'materialid_refistrationnumber': '', 'id': '1545032604363786242', 'stockid_mobile': '', 'srcorderid': 'sxo_20221102161317631600', 'returnbaseqty': '0',
             'materialid_iskfperiod': False, 'materialid_ispurchase': True, 'materialid_wide': '0', 'order_baseqty': '1', 'baseunit_id': '3', 'stockid_phone': '',
             'invoicedtaxamount': '0', 'auxid1_number': 'FZSX00098', 'mullabel': [], 'taxamount': '0', 'inputcoefficient': '0', 'materialid_barcode': '', 'baseunit_precision': '0',
             'materialid_prolicense': '', 'materialid_issale': True, 'returnqty': '0', 'materialid_maxinventoryqty': '0', 'custbillno': '', 'srcseq': '3', 'stockid_address': '',
             'src_billdate': '', 'src_bill_dis_rate': '0', 'invoiceddisamount': '0', 'materialid_duedatetype': '1', 'stockid_id': '1389149618935194624', 'disamount': '0',
             'materialid_tradeprice': '0', 'auxqty': '0', 'unit_id': '3', 'kfperiod': '0', 'materialid_bindsupplier': '', 'actnontaxamount': '0', 'entryinvoicestatus': '1',
             'materialid_name': '森花泉古方草本护肤系列 天门冬面膜45分钟直达真皮银耳深度补水', 'balanceamountfor': '0', 'regain_price': True, 'promote_ids': '', 'acttaxprice': '0', 'auxunittype': '0',
             'picture': 'https://mmecimage.cn/p/wxe6b89bd3689d4f57/HO9ulGV7f-lonvtgtolpTgEVvFN3rsVE1HuX-fPyrhM', 'materialid_entrust': False, 'invoicedbilldistribution': '0',
             'entrustamountfor': '0', 'cusmaterial_model_export': '', 'returnbillno': '', 'settleamountfor': '0', 'kftype': '', 'entryinvoicedqty': '0',
             'auxpropid_concattypeid': '1389953590776324096', 'fee': '0', 'materialid_number': 'P_SHQ_220406_69', 'materialid_model': '', 'set_entry_qty': '0', 'net_weight': '0',
             'entrusttaxamount': '0', 'unit_number': '支', 'serialqty': '0', 'materialid_kfperiodtype': '', 'gross_weight': '0', 'unit_conversiontype': '1',
             'auxprop_sku_export': '', 'package': '[["支",1.0,"3",1,0]]', 'inv_qty': '190', 'auxpropid_enable': '1', 'materialid_stockup_day': '3',
             'auxpropid_number': 'K_SHQ_MM_5P_0328', 'entrysettlestatus': 'C', 'set_entry_id': '0', 'srcbillno': 'sxo_20221102161317631600', 'unit_name': '支', 'entrustamount': '0',
             'material_model_export': '', 'srcbillno_hyperlink': ' ', 'promote_names': '', 'billdisdistribution': '0', 'settleamount': '0', 'auxid1_id': '1389953590776324096',
             'materialid_kfperiod': '0', 'linkfee': '0', 'materialid_purchaseprice': '0', 'unitcost': '0', 'materialid_taxrate': '0', 'disrate': '0',
             'auxpropid_materialid': '1399311012678622208', 'srcbilltypeid_id': 'sal_bill_order', 'srcbilltypeid_number': 'sal_bill_order', 'base_taxprice': '0',
             'eoutersrcinterid': '0', 'base_price': '0', 'prolicense': '', 'material_set_code': '', 'auxid1_name': '润泽补水面膜5片', 'materialid_checktype': '1',
             'material_category_export': '', 'distaxamount': '0', 'amount': '0', 'cost': '0', 'totalgrossweight': '0', 'unitcost_view': '0', 'stockid_enable': '1', 'kfdate': '',
             'billdisbeforeamount': '0', 'materialid_isserial': False, 'unsettleamount': '0', 'materialid_minsalesprice': '0', 'materialid_producingpace': '',
             'materialid_mininventoryqty': '0', 'conversionrate': '', 'materialid_remark': '', 'materialid_id': '1399311012678622208'}], 'cus_currency_enable': '1',
        'currencyid_number': 'CNY', 'dispatcher_phone': '', 'creatorid_number': 'qywx_woecicwaa6uysadjsgaw', 'totalamount': '1216', 'mullabel': [], 'deliverystatus': 'C',
        'customerid_addr': '', 'mulbilllabel': [], 'billdate': '2022-11-02', 'currencyid_enable': '1', 'customerid_invoicetype': '1', 'wf_tasktype': None,
        'billno': 'XSCK-20221102-0000', 'bill_dis_amount': '0', 'dispatcher_linkman': '', 'invoicetype': None, 'contact_info': '', 'cus_bear_fee_status': 'B', 'edit_pay_amt': '0',
        'customerid_number': 'omvAI5aCStkVbqRv9fKKXMn1Cd1g', 'uninvoiceamount': '1216', 'totalamountfor': '1216', 'contact_country_number': '001', 'delivery_time_view': '',
        'express_company_view': '顺丰快递', 'customerid_id': '1535585880100618240', 'iostatus': '0', 'billtypeid_number': 'sal_bill_outbound', 'billtypeid_id': 'sal_bill_outbound',
        'basecurrency_id': '1389106429918471168', 'voucher_period': '', 'allocate_rule': '1', 'modifierid_id': '10174784', 'customerid_pinyin': 'zn_omvAI5aCStkVbqRv9fKKXMn1Cd1g',
        'diffamount': '0', 'auditorid_id': '10456065', 'totalsettleamount': '1216', 'appid': '', 'totalpreamountfor': '0', 'contact_country_id': '1000001',
        'currencyid_priceprecision': '2', 'date': '', 'alter_reason': '', 'contact_phone': '13714724766', 'cus_bear_fee_detail': '', 'other_creditid': '0',
        'dispatcher_country_number': '001', 'sel_cost_allocation': '', 'currencyid_rate': '1', 'customerid_creditlimit': '0', 'totalunsettleamountfor': '0',
        'basecurrency_priceprecision': '2', 'dispatcher_address': '', 'cus_currency_exctype': '2', 'currencyid_isshowsign': False, 'custom_field__data': None, 'billstatus': 'C',
        'auditorid_name': '刘巍', 'cus_bear_amount': '0', 'vrp_entity': [], 'proxy_cost_fee': '0', 'alter_date': '', 'customerid_accountopenaddr': '', 'auditorid_number': 'test0607',
        'dispatcher_country_name': '中国', 'failurereason': '', 'accountcheck': '0', 'cus_bear_fee_entry': [], 'basecurrency_name': '人民币', 'totalpreamount': '0', 'outsidepkid': '',
        'deductible_subsist': False, 'remark': None, 'totalinsfinalamount': '1216', 'cus_currency_format': '', 'delivery_remark_view': '', 'bill_dis_rate': '0',
        'modifierid_name': '小量', 'customerid_fullpinyin': 'zhunian_omvAI5aCStkVbqRv9fKKXMn1Cd1g', 'isbatchchangerows': False, 'costvoucherid': '0', 'cus_bear_amountfor': '0',
        'currencyid_id': '1389106429918471168', 'cost_fee_detail': '', 'customerid_deduct': False, 'cus_exchangerate': '1', 'cus_currency_sign': '', 'invoiceno': ' ',
        'cus_currency_id': '1389106429918471168', 'alter_tag': False, 'auditorid_masterid': '0'}
