DATA = {
    'success': True,
    'reachPlugin': True,
    'data': {
        'auxunitid_name': '套',
        'isautosplit': False,
        'isfloat': False,
        'standardcurrencyid_name': '人民币',
        'modifierfield_id': '10174784',
        'number': 'test_tz_123456',
        'baseunitid_name': '套',
        'qtyinv': '0',
        'modifierfield_number': 'qywx_woecicwaa6uysadjsgaw',
        'enable': '1',
        'model': '',
        'id': '1393306133833218048',
        'auxtype5': False,
        'auxtype4': False,
        'secinventoryqty': '0',
        'saleunitid_name': '套',
        'images': [],
        'createrfield_id': '10174784',
        'computationrule': '1',
        'disabledate': '',
        'purchaseunitid_number': '套',
        'issubpart': False,
        'mullabel': [],
        'priceentity': [
            {
                'nearpurpricebilldate': '',
                'price_name': '',
                'price_minsaltaxprice': '0',
                'price_purchaseprice': '0',
                'price_distributionprice': '99999',
                'price_minpurprice': '0',
                'nearpurcostcreatetime': '',
                'price_maxpurchaseprice': '0',
                'nearsalpricebilldate': '',
                'price_nearpurtaxprice': '0',
                'price_minsalprice': '0',
                'id': '1393306133833219074',
                'price_minpurtaxprice': '0',
                'price_costprice': '0',
                'nearpurpriceseq': '0',
                'price_minsalesprice': '9999',
                'price_saleprice10': '0',
                'nearsalcostaudittime': '',
                'price_saleprice1': '0',
                'price_saleprice2': '0',
                'price_saleprice3': '0',
                'price_saleprice8': '0',
                'price_nearsalprice': '0',
                'price_saleprice9': '0',
                'price_saleprice4': '0',
                'nearpurcostseq': '0',
                'price_saleprice5': '0',
                'price_saleprice6': '0',
                'price_saleprice7': '0',
                'price_tradeprice': '22',
                'price_barcode': '',
                'nearsalpriceaudittime': '',
                'price_unitid_id': '1393305614477719552',
                'nearpurpricecreatetime': '',
                'nearpurcostbilldate': '',
                'nearsalpricecreatetime': '',
                'price_maxpurtaxprice': '0',
                'price_retailprice': '9999',
                'nearsalcostbilldate': '',
                'nearpurpriceaudittime': '',
                'seq': '1',
                'price_maxpurprice': '0',
                'price_unitid_number': '套',
                'price_unitid_name': '套',
                'price_skuid': '0',
                'price_nearpurunitcost': '0',
                'price_maxsalprice': '0',
                'nearsalcostcreatetime': '',
                'price_nearsalunitcost': '0',
                'price_nearsaltaxprice': '0',
                'price_maxsaltaxprice': '0',
                'nearsalcostseq': '0',
                'nearpurcostaudittime': '',
                'price_nearpurprice': '0',
                'nearsalpriceseq': '0'
            }
        ],
        'leadtime': '0',
        'fullpinyin': 'ceshitaozhuang',
        'auxunitid_number': '套',
        'createtime1': '',
        'kfperiodtype': '',
        'saleprice8': '0',
        'saleprice9': '0',
        'saleprice6': '0',
        'saleprice7': '0',
        'saleprice4': '0',
        'saleprice5': '0',
        'saleprice2': '0',
        'saleprice3': '0',
        'inv_mgr_type': '0',
        'isserial': False,
        'standardcurrencyid_id': '1389106429918471168',
        'sharetimes': '0',
        'saleprice1': '0',
        'helpcode': 'cstz',
        'kfperiod': '0',
        'ismulti_unit': False,
        'createtime': '2022-04-07 09:27:53',
        'isbatchcost': False,
        'entrust': False,
        'isbatch': False,
        'url': '',
        'stockup_day': '0',
        'refistrationnumber': '',
        'saleprice10': '0',
        'parent_name': '默认分类',
        'fixunitcount': '0',
        'mininventoryqty': '0',
        'baseunitid_id': '1393305614477719552',
        'isinvauxset': False,
        'isassembly': False,
        'net_weight': '0',
        'txtbarcode': '',
        'storeunitid_name': '套',
        'checktype': '2',
        'high': '0',
        'modifytime1': '',
        'distributionprice': '99999',
        'attachments_url': [],
        'producingpace': '',
        'purchaseunitid_name': '套',
        'iskfperiod': False,
        'gross_weight': '0',
        'barcode': '',
        'taxrate': '0',
        'custom_field__data': None,
        'store_entity': [],
        'barcodeentity': [],
        'saleunitid_id': '1393305614477719552',
        'volume': '0',
        'createrfield_number': 'qywx_woecicwaa6uysadjsgaw',
        'pinyin': 'cstz',
        'parent_id': '1389149189690125312',
        'standardcurrencyid_number': 'CNY',
        'sharedate': '',
        'name': '测试套装',
        'storeunitid_number': '套',
        'isweight': False,
        'costmethod': '1',
        'baseunitid_number': '套',
        'saleunitid_number': '套',
        'isauxcost': False,
        'modifytime': '2022-04-07 09:30:34',
        'auxentity': [],
        'issale': True,
        'isasstattr': False,
        'multicount': '0',
        'remark': '',
        'createrfield_name': 'woeci-CwAA6UYsadJsGaW4slm5jccVkQ',
        'storeunitid_id': '1393305614477719552',
        'purchaseunitid_id': '1393305614477719552',
        'parent_number': 'SPFL00001',
        'auxunitid_id': '1393305614477719552',
        'alarmday': '0',
        'bomentity': [
            {
                'bomauxid1_groupid_id': '1',
                'bomauxid1_parent_name': '净含量',
                'unitid_name': '支',
                'bomauxid1_name': '200ml【院线正品】',
                'materialid_number': 'P__220406_27',
                'materialid_parent_number': 'SPFL00001',
                'bomauxid1_groupid_number': '01',
                'rate': '0.5',
                'price': '11',
                'entrycostprice': '0',
                'bomauxid1_number': 'FZSX00114',
                'id': '1393306133833218049',
                'bomaux_number': 'YF_BLP_22030401',
                'bomaux_auxid1_number': 'FZSX00114',
                'seq': '1',
                'bomaux_name': '200ml【院线正品】',
                'amount': '11',
                'costamount': '0',
                'bomauxid1_parent_id': '1',
                'materialid_baseunitid_id': '3',
                'unitid_id': '3',
                'bomauxid1_groupid_name': '净含量',
                'materialreplace': [],
                'materialid_name': '域发白柳皮控油平衡洗发露',
                'materialid_parent_id': '1389149189690125312',
                'isfree': False,
                'bomaux_auxid1_name': '200ml【院线正品】',
                'materialid_baseunitid_name': '支',
                'bomaux_auxid1_id': '1389954785179886592',
                'bomauxid1_id': '1389954785179886592',
                'unitid_number': '支',
                'qty': '1.0000000000',
                'materialid_baseunitid_number': '支',
                'bomaux_id': '1392638716459120640',
                'materialid_parent_name': '默认分类',
                'bomauxid1_parent_number': '01',
                'materialid_id': '1392638716048079872',
                'isreplace': False
            },
            {
                'bomauxid1_groupid_id': '1',
                'bomauxid1_parent_name': '净含量',
                'unitid_name': '支',
                'bomauxid1_name': '60ml【院线正品】',
                'materialid_number': 'P__220406_32',
                'materialid_parent_number': 'SPFL00001',
                'bomauxid1_groupid_number': '01',
                'rate': '0.5',
                'price': '11',
                'entrycostprice': '0',
                'bomauxid1_number': 'FZSX00120',
                'id': '1393306133833218050',
                'bomaux_number': 'YF_YT_22-3-4-3',
                'bomaux_auxid1_number': 'FZSX00120',
                'seq': '2',
                'bomaux_name': '60ml【院线正品】',
                'amount': '11',
                'costamount': '0',
                'bomauxid1_parent_id': '1',
                'materialid_baseunitid_id': '3',
                'unitid_id': '3',
                'bomauxid1_groupid_name': '净含量',
                'materialreplace': [],
                'materialid_name': '域发液体敷料头皮营养敷料',
                'materialid_parent_id': '1389149189690125312',
                'isfree': False,
                'bomaux_auxid1_name': '60ml【院线正品】',
                'materialid_baseunitid_name': '支',
                'bomaux_auxid1_id': '1389954855979740160',
                'bomauxid1_id': '1389954855979740160',
                'unitid_number': '支',
                'qty': '1.0000000000',
                'materialid_baseunitid_number': '支',
                'bomaux_id': '1392638684196530176',
                'materialid_parent_name': '默认分类',
                'bomauxid1_parent_number': '01',
                'materialid_id': '1392638683693214720',
                'isreplace': False
            }
        ],
        'prolicense': '',
        'modifierfield_name': 'woeci-CwAA6UYsadJsGaW4slm5jccVkQ',
        'wide': '0',
        'attachmentcountfield': '0',
        'maxinventoryqty': '0',
        'length': '0',
        'ispurchase': False,
        'bomprice': '0',
        'istaxfree': False,
        'conversionrate': '',
        'isshowauxbarcode': False
    },
    'errorCode': 'success'
}

data2 = {
    'auxunitid_name': '套',
    'isautosplit': False,
    'isfloat': False,
    'standardcurrencyid_name': '人民币',
    'modifierfield_id': '10174784',
    'number': 'P_KFM_WNN_BZC_220315_27',
    'baseunitid_name': '套',
    'qtyinv': '0',
    'modifierfield_number': 'qywx_woecicwaa6uysadjsgaw',
    'enable': '1',
    'model': '',
    'id': '1393468457894312960',
    'auxtype5': False,
    'auxtype4': False,
    'secinventoryqty': '0',
    'saleunitid_name': '套',
    'images': [],
    'createrfield_id': '10174784',
    'computationrule': '1',
    'disabledate': '',
    'purchaseunitid_number': '套',
    'issubpart': False,
    'mullabel': [],
    'priceentity': [
        {
            'nearpurpricebilldate': '',
            'price_name': '',
            'price_minsaltaxprice': '0',
            'price_purchaseprice': '0',
            'price_distributionprice': '0',
            'price_minpurprice': '0',
            'nearpurcostcreatetime': '',
            'price_maxpurchaseprice': '0',
            'nearsalpricebilldate': '',
            'price_nearpurtaxprice': '0',
            'price_minsalprice': '0',
            'id': '1393468457894311938',
            'price_minpurtaxprice': '0',
            'price_costprice': '0',
            'nearpurpriceseq': '0',
            'price_minsalesprice': '0',
            'price_saleprice10': '0',
            'nearsalcostaudittime': '',
            'price_saleprice1': '0',
            'price_saleprice2': '0',
            'price_saleprice3': '0',
            'price_saleprice8': '0',
            'price_nearsalprice': '0',
            'price_saleprice9': '0',
            'price_saleprice4': '0',
            'nearpurcostseq': '0',
            'price_saleprice5': '0',
            'price_saleprice6': '0',
            'price_saleprice7': '0',
            'price_tradeprice': '564',
            'price_barcode': '',
            'nearsalpriceaudittime': '',
            'price_unitid_id': '1393305614477719552',
            'nearpurpricecreatetime': '',
            'nearpurcostbilldate': '',
            'nearsalpricecreatetime': '',
            'price_maxpurtaxprice': '0',
            'price_retailprice': '0',
            'nearsalcostbilldate': '',
            'nearpurpriceaudittime': '',
            'seq': '1',
            'price_maxpurprice': '0',
            'price_unitid_number': '套',
            'price_unitid_name': '套',
            'price_skuid': '0',
            'price_nearpurunitcost': '0',
            'price_maxsalprice': '0',
            'nearsalcostcreatetime': '',
            'price_nearsalunitcost': '0',
            'price_nearsaltaxprice': '0',
            'price_maxsaltaxprice': '0',
            'nearsalcostseq': '0',
            'nearpurcostaudittime': '',
            'price_nearpurprice': '0',
            'nearsalpriceseq': '0'
        }
    ],
    'leadtime': '0',
    'fullpinyin': 'jisuyilaixingpiyanpingzhangxiufuhulitaozhuang',
    'auxunitid_number': '套',
    'createtime1': '',
    'kfperiodtype': '',
    'saleprice8': '0',
    'saleprice9': '0',
    'saleprice6': '0',
    'saleprice7': '0',
    'saleprice4': '0',
    'saleprice5': '0',
    'saleprice2': '0',
    'saleprice3': '0',
    'inv_mgr_type': '0',
    'isserial': False,
    'standardcurrencyid_id': '1389106429918471168',
    'sharetimes': '0',
    'saleprice1': '0',
    'helpcode': 'jsylxpypzxfhltz',
    'kfperiod': '0',
    'ismulti_unit': False,
    'createtime': '2022-04-07 14:33:51',
    'isbatchcost': False,
    'entrust': False,
    'isbatch': False,
    'url': '',
    'stockup_day': '0',
    'refistrationnumber': '',
    'saleprice10': '0',
    'parent_name': '套装',
    'fixunitcount': '0',
    'mininventoryqty': '0',
    'baseunitid_id': '1393305614477719552',
    'isinvauxset': False,
    'isassembly': False,
    'net_weight': '0',
    'txtbarcode': '',
    'storeunitid_name': '套',
    'checktype': '2',
    'high': '0',
    'modifytime1': '',
    'distributionprice': '0',
    'attachments_url': [],
    'producingpace': '',
    'purchaseunitid_name': '套',
    'iskfperiod': False,
    'gross_weight': '0',
    'barcode': '',
    'taxrate': '0',
    'custom_field__data': None,
    'store_entity': [],
    'barcodeentity': [],
    'saleunitid_id': '1393305614477719552',
    'volume': '0',
    'createrfield_number': 'qywx_woecicwaa6uysadjsgaw',
    'pinyin': 'jsylxpypzxfhltz',
    'parent_id': '1393458694343130112',
    'standardcurrencyid_number': 'CNY',
    'sharedate': '',
    'name': '激素依赖性皮炎屏障修复护理套装',
    'storeunitid_number': '套',
    'isweight': False,
    'costmethod': '1',
    'baseunitid_number': '套',
    'saleunitid_number': '套',
    'isauxcost': False,
    'modifytime': '2022-04-07 14:53:05',
    'auxentity': [],
    'issale': True,
    'isasstattr': False,
    'multicount': '0',
    'remark': '',
    'createrfield_name': 'woeci-CwAA6UYsadJsGaW4slm5jccVkQ',
    'storeunitid_id': '1393305614477719552',
    'purchaseunitid_id': '1393305614477719552',
    'parent_number': 'SPFL00002',
    'auxunitid_id': '1393305614477719552',
    'alarmday': '0',
    'bomentity': [
        {
            'bomauxid1_groupid_id': '1',
            'bomauxid1_parent_name': '净含量',
            'unitid_name': '支',
            'bomauxid1_name': '类人胶原蛋白敷料粉5片',
            'materialid_number': 'P_KFM_220406_54',
            'materialid_parent_number': 'SPFL00001',
            'bomauxid1_groupid_number': '01',
            'rate': '0.2624',
            'price': '148',
            'entrycostprice': '0',
            'bomauxid1_number': 'FZSX00133',
            'id': '1393468457894312961',
            'bomaux_number': 'K_KFM_MM_R5P_0328',
            'bomaux_auxid1_number': 'FZSX00133',
            'seq': '1',
            'bomaux_name': '类人胶原蛋白敷料粉5片',
            'amount': '148',
            'costamount': '0',
            'bomauxid1_parent_id': '1',
            'materialid_baseunitid_id': '3',
            'unitid_id': '3',
            'bomauxid1_groupid_name': '净含量',
            'materialreplace': [],
            'materialid_name': '可复美类人胶原蛋白敷料（粉色5片）',
            'materialid_parent_id': '1389149189690125312',
            'isfree': False,
            'bomaux_auxid1_name': '类人胶原蛋白敷料粉5片',
            'materialid_baseunitid_name': '支',
            'bomaux_auxid1_id': '1392639015269727232',
            'bomauxid1_id': '1392639015269727232',
            'unitid_number': '支',
            'qty': '1.0000000000',
            'materialid_baseunitid_number': '支',
            'bomaux_id': '1392639020353218561',
            'materialid_parent_name': '默认分类',
            'bomauxid1_parent_number': '01',
            'materialid_id': '1392639019858291712',
            'isreplace': False
        },
        {
            'bomauxid1_groupid_id': '1',
            'bomauxid1_parent_name': '净含量',
            'unitid_name': '支',
            'bomauxid1_name': '120ml',
            'materialid_number': 'P_WNN_220406_65',
            'materialid_parent_number': 'SPFL00001',
            'bomauxid1_groupid_number': '01',
            'rate': '0.4574',
            'price': '258',
            'entrycostprice': '0',
            'bomauxid1_number': 'FZSX00071',
            'id': '1393468457894312962',
            'bomaux_number': 'K_WNN_SMSFS_120_0328',
            'bomaux_auxid1_number': 'FZSX00071',
            'seq': '2',
            'bomaux_name': '120ml',
            'amount': '258',
            'costamount': '0',
            'bomauxid1_parent_id': '1',
            'materialid_baseunitid_id': '3',
            'unitid_id': '3',
            'bomauxid1_groupid_name': '净含量',
            'materialreplace': [],
            'materialid_name': '薇诺娜舒敏保湿润肤水',
            'materialid_parent_id': '1389149189690125312',
            'isfree': False,
            'bomaux_auxid1_name': '120ml',
            'materialid_baseunitid_name': '支',
            'bomaux_auxid1_id': '1389953152479945728',
            'bomauxid1_id': '1389953152479945728',
            'unitid_number': '支',
            'qty': '1.0000000000',
            'materialid_baseunitid_number': '支',
            'bomaux_id': '1392639543835916288',
            'materialid_parent_name': '默认分类',
            'bomauxid1_parent_number': '01',
            'materialid_id': '1392639543408098304',
            'isreplace': False
        },
        {
            'bomauxid1_groupid_id': '1',
            'bomauxid1_parent_name': '净含量',
            'unitid_name': '支',
            'bomauxid1_name': '150ml',
            'materialid_number': 'P_BZC_220406_50',
            'materialid_parent_number': 'SPFL00001',
            'bomauxid1_groupid_number': '01',
            'rate': '0.2802',
            'price': '158',
            'entrycostprice': '0',
            'bomauxid1_number': 'FZSX00044',
            'id': '1393468457894312963',
            'bomaux_number': 'K_BZC_PW_150_0328',
            'bomaux_auxid1_number': 'FZSX00044',
            'seq': '3',
            'bomaux_name': '150ml',
            'amount': '158',
            'costamount': '0',
            'bomauxid1_parent_id': '1',
            'materialid_baseunitid_id': '3',
            'unitid_id': '3',
            'bomauxid1_groupid_name': '净含量',
            'materialreplace': [],
            'materialid_name': '百植萃舒缓修护保湿喷雾',
            'materialid_parent_id': '1389149189690125312',
            'isfree': False,
            'bomaux_auxid1_name': '150ml',
            'materialid_baseunitid_name': '支',
            'bomaux_auxid1_id': '1389950401142349824',
            'bomauxid1_id': '1389950401142349824',
            'unitid_number': '支',
            'qty': '1.0000000000',
            'materialid_baseunitid_number': '支',
            'bomaux_id': '1392639411111361536',
            'materialid_parent_name': '默认分类',
            'bomauxid1_parent_number': '01',
            'materialid_id': '1392639410683541504',
            'isreplace': False
        }
    ],
    'prolicense': '',
    'modifierfield_name': 'woeci-CwAA6UYsadJsGaW4slm5jccVkQ',
    'wide': '0',
    'attachmentcountfield': '0',
    'maxinventoryqty': '0',
    'length': '0',
    'ispurchase': False,
    'bomprice': '0',
    'istaxfree': False,
    'conversionrate': '',
    'isshowauxbarcode': False
}

data = [
    {
        "_id": "u_grPWRXGoW5",
        "total": 23400,
        "count": 2,
        "hot_val": 6100
    }, {
        "_id": "_sys_superior_",
        "total": 130900,
        "count": 6,
        "hot_val": 41800
    },

    {
        "_id": "d_9Rk9TDXjRF",
        "total": 14800,
        "count": 1,
        "hot_val": 2600
    },

    {
        "_id": "d_ChHtFZnJxQ",
        "total": 235700,
        "count": 8,
        "hot_val": 62000
    },

    {
        "_id": "d_bpoFSJVHFP",
        "total": 47200,
        "count": 1,
        "hot_val": 12200
    },

    {
        "_id": "d_J7mYBWwGu4",
        "total": 262300,
        "count": 10,
        "hot_val": 58900
    },

    {
        "_id": "d_oGwHRwY2mE",
        "total": 248100,
        "count": 8,
        "hot_val": 56900
    },

    {
        "_id": "d_ujHJHBRtyn",
        "total": 323900,
        "count": 16,
        "hot_val": 57600
    },

    {
        "_id": "d_SoBpMN5kUF",
        "total": 3328100,
        "count": 127,
        "hot_val": 890100
    },

    {
        "_id": "d_vi8kF8ZZ7R",
        "total": 1953000,
        "count": 80,
        "hot_val": 548800
    }]

# 6,498,300
total = count = 0
for item in data:
    total += item.get("total")
    count += item.get("count")

print(total)
print(total - 6498300)
print(count)
data3 = [{
    "order_sum": 226800.0,
    "order_count": 9,
    "order_hot_val": 41400,
    "doc_id": "_sys_superior_"
},
    {
        "order_sum": 14800.0,
        "order_count": 1,
        "order_hot_val": 2600,
        "doc_id": "d_9Rk9TDXjRF"
    },
    {
        "order_sum": 174600.0,
        "order_count": 4,
        "order_hot_val": 46500,
        "doc_id": "d_ChHtFZnJxQ"
    },
    {
        "order_sum": 23400.0,
        "order_count": 2,
        "order_hot_val": 6100,
        "doc_id": "d_EPPBVArrCw"
    },
    {
        "order_sum": 182700.0,
        "order_count": 6,
        "order_hot_val": 48800,
        "doc_id": "d_J7mYBWwGu4"
    },
    {
        "order_sum": 971600.0,
        "order_count": 38,
        "order_hot_val": 224500,
        "doc_id": "d_SoBpMN5kUF"
    },
    {
        "order_sum": 37600.0,
        "order_count": 2,
        "order_hot_val": 9000,
        "doc_id": "d_oGwHRwY2mE"
    },
    {
        "order_sum": 164000.0,
        "order_count": 7,
        "order_hot_val": 31100,
        "doc_id": "d_ujHJHBRtyn"
    },
    {
        "order_sum": 918300.0,
        "order_count": 35,
        "order_hot_val": 266900,
        "doc_id": "d_vi8kF8ZZ7R"
    }]

data4 = [{
        "order_sum": 226800.0,
        "order_count": 9,
        "order_hot_val": 41400,
        "doc_id": "_sys_superior_"
    },
    {
        "order_sum": 14800.0,
        "order_count": 1,
        "order_hot_val": 2600,
        "doc_id": "d_9Rk9TDXjRF"
    },
    {
        "order_sum": 174600.0,
        "order_count": 4,
        "order_hot_val": 46500,
        "doc_id": "d_ChHtFZnJxQ"
    },
    {
        "order_sum": 23400.0,
        "order_count": 2,
        "order_hot_val": 6100,
        "doc_id": "d_EPPBVArrCw"
    },
    {
        "order_sum": 182700.0,
        "order_count": 6,
        "order_hot_val": 48800,
        "doc_id": "d_J7mYBWwGu4"
    },
    {
        "order_sum": 985089.1344383057,
        "order_count": 39,
        "order_hot_val": 227300,
        "doc_id": "d_SoBpMN5kUF"
    },
    {
        "order_sum": 37600.0,
        "order_count": 2,
        "order_hot_val": 9000,
        "doc_id": "d_oGwHRwY2mE"
    },
    {
        "order_sum": 164000.0,
        "order_count": 7,
        "order_hot_val": 31100,
        "doc_id": "d_ujHJHBRtyn"
    },
    {
        "order_sum": 973910.8655616943,
        "order_count": 36,
        "order_hot_val": 277200,
        "doc_id": "d_vi8kF8ZZ7R"
    }]
